/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\static\models\a5\a5_v2.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Body1: THREE.Mesh
    ['Body1_(1)']: THREE.Mesh
    ['Body1_(2)']: THREE.Mesh
    ['Body1_(3)']: THREE.Mesh
    Body2: THREE.Mesh
    ['Body2_(1)']: THREE.Mesh
    Body3: THREE.Mesh
    ['Body3_(1)']: THREE.Mesh
    Body4: THREE.Mesh
    ['Body4_(1)']: THREE.Mesh
    Body48: THREE.Mesh
    Body49: THREE.Mesh
    Body50: THREE.Mesh
    Body51: THREE.Mesh
    Body52: THREE.Mesh
    Body53: THREE.Mesh
  }
  materials: {
    ['ABS (White).003']: THREE.MeshStandardMaterial
    ['Steel - Satin.007']: THREE.MeshStandardMaterial
    ['ABS (White).004']: THREE.MeshStandardMaterial
    Generic: THREE.MeshStandardMaterial
  }
  animations: any // GLTFAction[]
}

const Model = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF('/models/a5/a5_v2.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Body1.geometry} material={materials['ABS (White).003']} scale={10} />
        <mesh geometry={nodes['Body1_(1)'].geometry} material={materials['ABS (White).003']} scale={10} />
        <mesh geometry={nodes['Body1_(2)'].geometry} material={materials['Steel - Satin.007']} scale={10} />
        <mesh geometry={nodes['Body1_(3)'].geometry} material={materials['ABS (White).004']} scale={10} />
        <mesh geometry={nodes.Body2.geometry} material={materials['Steel - Satin.007']} scale={10} />
        <mesh geometry={nodes['Body2_(1)'].geometry} material={materials.Generic} scale={10} />
        <mesh geometry={nodes.Body3.geometry} material={materials['Steel - Satin.007']} scale={10} />
        <mesh geometry={nodes['Body3_(1)'].geometry} material={materials.Generic} scale={10} />
        <mesh geometry={nodes.Body4.geometry} material={materials['ABS (White).004']} scale={10} />
        <mesh geometry={nodes['Body4_(1)'].geometry} material={materials['Steel - Satin.007']} scale={10} />
        <mesh geometry={nodes.Body48.geometry} material={materials['ABS (White).004']} scale={10} />
        <mesh geometry={nodes.Body49.geometry} material={materials['ABS (White).004']} scale={10} />
        <mesh geometry={nodes.Body50.geometry} material={materials['ABS (White).004']} scale={10} />
        <mesh geometry={nodes.Body51.geometry} material={materials['ABS (White).004']} scale={10} />
        <mesh geometry={nodes.Body52.geometry} material={materials['ABS (White).004']} scale={10} />
        <mesh geometry={nodes.Body53.geometry} material={materials['ABS (White).004']} scale={10} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/a5/a5_v2.glb')
export default Model
