/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\static\models\agenda.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Front: THREE.Mesh
    Back: THREE.Mesh
    SidebarSmall: THREE.Mesh
    SignDiario: THREE.Mesh
    SignProgettoX: THREE.Mesh
    SidebarBig: THREE.Mesh
    JointUp: THREE.Mesh
    JointDown: THREE.Mesh
    LaceDL: THREE.Mesh
    LaceUL: THREE.Mesh
    RedCircle: THREE.Mesh
    Stripes: THREE.Mesh
    LaceUB: THREE.Mesh
    LaceDB: THREE.Mesh
  }
  materials: {
    ['3d texture bianco']: THREE.MeshStandardMaterial
    ['3d texture rossa (1).001']: THREE.MeshStandardMaterial
    ['3d texture rossa (2) (1).001']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['3d texture rossa (2) (1)']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
  }
  animations: any// GLTFAction[]
}

const Model = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF('/models/agenda.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Front.geometry} material={materials['3d texture bianco']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Back.geometry} material={materials['3d texture bianco']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.SidebarSmall.geometry} material={materials['3d texture rossa (1).001']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.SignDiario.geometry} material={materials['3d texture rossa (2) (1).001']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.SignProgettoX.geometry} material={materials['3d texture rossa (2) (1).001']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.SidebarBig.geometry} material={materials['3d texture rossa (1).001']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.JointUp.geometry} material={materials['ABS (White)']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.JointDown.geometry} material={materials['ABS (White)']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.LaceDL.geometry} material={materials['ABS (White)']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.LaceUL.geometry} material={materials['ABS (White)']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.RedCircle.geometry} material={materials['3d texture rossa (2) (1)']} position={[-0.003, 0, 0.001]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Stripes.geometry} material={materials['Steel - Satin']} position={[-0.003, 0, 0.001]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.LaceUB.geometry} material={materials['3d texture rossa (1).001']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.LaceDB.geometry} material={materials['3d texture rossa (1).001']} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/models/agenda.glb')

export default Model