/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\static\models\a6\a6_v3.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Body1007: THREE.Mesh
    Body10: THREE.Mesh
    Body11: THREE.Mesh
    Body12: THREE.Mesh
    Body13: THREE.Mesh
    Body14: THREE.Mesh
    Body15: THREE.Mesh
    Body16: THREE.Mesh
    Body2: THREE.Mesh
    Body3: THREE.Mesh
    Body4: THREE.Mesh
    Body5: THREE.Mesh
    Body6: THREE.Mesh
    Body7: THREE.Mesh
    Body8: THREE.Mesh
    Body9: THREE.Mesh
    Body1: THREE.Mesh
    Body1001: THREE.Mesh
    Body1002: THREE.Mesh
    Body1003: THREE.Mesh
    Body1004: THREE.Mesh
    Body1005: THREE.Mesh
    Body1006: THREE.Mesh
    Body1008: THREE.Mesh
    Body11001: THREE.Mesh
    Body12001: THREE.Mesh
    Body13001: THREE.Mesh
    Body14001: THREE.Mesh
    Body15001: THREE.Mesh
    Body16001: THREE.Mesh
    Body2001: THREE.Mesh
    Body3001: THREE.Mesh
    Body4001: THREE.Mesh
    Body5001: THREE.Mesh
    Body6001: THREE.Mesh
    Body7001: THREE.Mesh
    Body8001: THREE.Mesh
    Body9001: THREE.Mesh
  }
  materials: {
    ['3d texture rossa (1).003']: THREE.MeshStandardMaterial
    ['3d texture rossa (2) (1).009']: THREE.MeshStandardMaterial
    ['3d texture bianco.003']: THREE.MeshStandardMaterial
    ['ABS (White).013']: THREE.MeshStandardMaterial
    ['3d texture crema']: THREE.MeshStandardMaterial
    ['3d texture rossa (2) (1).010']: THREE.MeshStandardMaterial
    ['3d txture celeste.004']: THREE.MeshStandardMaterial
  }
  animations: any//GLTFAction[]
}

const Model = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF('/models/a6/a6_v3.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.001}>
        <group position={[-3.961, 1.436, 0.038]} rotation={[-Math.PI, 0, -Math.PI]}>
          <mesh geometry={nodes.Body1008.geometry} material={materials['ABS (White).013']} scale={10} />
          <mesh geometry={nodes.Body11001.geometry} material={materials['ABS (White).013']} scale={10} />
          <mesh geometry={nodes.Body12001.geometry} material={materials['ABS (White).013']} scale={10} />
          <mesh geometry={nodes.Body13001.geometry} material={materials['3d texture rossa (2) (1).010']} scale={10} />
          <mesh geometry={nodes.Body14001.geometry} material={materials['ABS (White).013']} scale={10} />
          <mesh geometry={nodes.Body15001.geometry} material={materials['ABS (White).013']} scale={10} />
          <mesh geometry={nodes.Body16001.geometry} material={materials['3d txture celeste.004']} scale={10} />
          <mesh geometry={nodes.Body2001.geometry} material={materials['ABS (White).013']} scale={10} />
          <mesh geometry={nodes.Body3001.geometry} material={materials['ABS (White).013']} scale={10} />
          <mesh geometry={nodes.Body4001.geometry} material={materials['ABS (White).013']} scale={10} />
          <mesh geometry={nodes.Body5001.geometry} material={materials['ABS (White).013']} scale={10} />
          <mesh geometry={nodes.Body6001.geometry} material={materials['ABS (White).013']} scale={10} />
          <mesh geometry={nodes.Body7001.geometry} material={materials['ABS (White).013']} scale={10} />
          <mesh geometry={nodes.Body8001.geometry} material={materials['ABS (White).013']} scale={10} />
          <mesh geometry={nodes.Body9001.geometry} material={materials['ABS (White).013']} scale={10} />
        </group>
        <mesh geometry={nodes.Body1007.geometry} material={materials['3d texture rossa (1).003']} scale={10} />
        <mesh geometry={nodes.Body10.geometry} material={materials['3d texture rossa (2) (1).009']} scale={10} />
        <mesh geometry={nodes.Body11.geometry} material={materials['3d texture rossa (2) (1).009']} scale={10} />
        <mesh geometry={nodes.Body12.geometry} material={materials['3d texture rossa (2) (1).009']} scale={10} />
        <mesh geometry={nodes.Body13.geometry} material={materials['3d texture rossa (2) (1).009']} scale={10} />
        <mesh geometry={nodes.Body14.geometry} material={materials['3d texture rossa (2) (1).009']} scale={10} />
        <mesh geometry={nodes.Body15.geometry} material={materials['3d texture rossa (2) (1).009']} scale={10} />
        <mesh geometry={nodes.Body16.geometry} material={materials['3d texture rossa (2) (1).009']} scale={10} />
        <mesh geometry={nodes.Body2.geometry} material={materials['3d texture rossa (2) (1).009']} scale={10} />
        <mesh geometry={nodes.Body3.geometry} material={materials['3d texture rossa (2) (1).009']} scale={10} />
        <mesh geometry={nodes.Body4.geometry} material={materials['3d texture rossa (2) (1).009']} scale={10} />
        <mesh geometry={nodes.Body5.geometry} material={materials['3d texture rossa (2) (1).009']} scale={10} />
        <mesh geometry={nodes.Body6.geometry} material={materials['3d texture rossa (2) (1).009']} scale={10} />
        <mesh geometry={nodes.Body7.geometry} material={materials['3d texture rossa (2) (1).009']} scale={10} />
        <mesh geometry={nodes.Body8.geometry} material={materials['3d texture rossa (2) (1).009']} scale={10} />
        <mesh geometry={nodes.Body9.geometry} material={materials['3d texture rossa (2) (1).009']} scale={10} />
        <mesh geometry={nodes.Body1.geometry} material={materials['3d texture bianco.003']} scale={10} />
        <mesh geometry={nodes.Body1001.geometry} material={materials['3d texture rossa (1).003']} scale={10} />
        <mesh geometry={nodes.Body1002.geometry} material={materials['ABS (White).013']} scale={10} />
        <mesh geometry={nodes.Body1003.geometry} material={materials['ABS (White).013']} scale={10} />
        <mesh geometry={nodes.Body1004.geometry} material={materials['ABS (White).013']} scale={10} />
        <mesh geometry={nodes.Body1005.geometry} material={materials['ABS (White).013']} scale={10} />
        <mesh geometry={nodes.Body1006.geometry} material={materials['3d texture crema']} scale={10} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/a6/a6_v3.glb')

export default Model