/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 static/models/exploding.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type ActionName = 'Action'

interface GLTFAction extends THREE.AnimationClip {
  name: ActionName
}

type GLTFResult = GLTF & {
  nodes: {
    Body1: THREE.Mesh
    Body1_1: THREE.Mesh
    Body1_2: THREE.Mesh
    Body1_3: THREE.Mesh
    Body1_4: THREE.Mesh
    Body1_5: THREE.Mesh
  }
  materials: {
    ['3d texture bianco']: THREE.MeshStandardMaterial
    ['3d texture rossa (1).001']: THREE.MeshStandardMaterial
    ['3d texture rossa (2) (1).001']: THREE.MeshStandardMaterial
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['3d texture rossa (2) (1)']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

const Model = (props: JSX.IntrinsicElements['group']) => {
  const group = React.useRef<THREE.Group>(null)
  const { nodes, materials, animations } = useGLTF('/models/exploding.glb') as GLTFResult
  const { actions } = useAnimations(animations, group)

  const handleClick = (actionName: ActionName) => {
    if (actions && actions[actionName]) {
      actions[actionName].reset().play();
    }
  };

  React.useEffect(() => {
    console.log('Actions:', actions.Action);
    if (actions) {
      Object.keys(actions).forEach(actionName => {
        actions[actionName as ActionName]?.reset().play(); // Play all available actions on load
      });
    }
  }, [actions]);

  return (
    <group {...props} dispose={null} onClick={() => handleClick('Action')} >
      <group name="Scene">
        <group name="Front" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh name="Body1" geometry={nodes.Body1.geometry} material={materials['3d texture bianco']} />
          <mesh name="Body1_1" geometry={nodes.Body1_1.geometry} material={materials['3d texture rossa (1).001']} />
          <mesh name="Body1_2" geometry={nodes.Body1_2.geometry} material={materials['3d texture rossa (2) (1).001']} />
          <mesh name="Body1_3" geometry={nodes.Body1_3.geometry} material={materials['ABS (White)']} />
          <mesh name="Body1_4" geometry={nodes.Body1_4.geometry} material={materials['3d texture rossa (2) (1)']} />
          <mesh name="Body1_5" geometry={nodes.Body1_5.geometry} material={materials['Steel - Satin']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/exploding.glb')

export default Model