/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\static\models\tascabile\tascabile_v1.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Body1: THREE.Mesh
    Body1001: THREE.Mesh
    ['Body1_(1)']: THREE.Mesh
    Body1002: THREE.Mesh
    Body10: THREE.Mesh
    ['Body10_(1)']: THREE.Mesh
    Body11: THREE.Mesh
    ['Body11_(1)']: THREE.Mesh
    Body12: THREE.Mesh
    Body13: THREE.Mesh
    Body14: THREE.Mesh
    Body15: THREE.Mesh
    Body16: THREE.Mesh
    Body17: THREE.Mesh
    Body18: THREE.Mesh
    Body19: THREE.Mesh
    ['Body2_(1)']: THREE.Mesh
    Body20: THREE.Mesh
    Body21: THREE.Mesh
    Body22: THREE.Mesh
    Body23: THREE.Mesh
    Body24: THREE.Mesh
    Body25: THREE.Mesh
    Body26: THREE.Mesh
    Body27: THREE.Mesh
    Body28: THREE.Mesh
    Body29: THREE.Mesh
    Body3: THREE.Mesh
    Body30: THREE.Mesh
    Body31: THREE.Mesh
    Body32: THREE.Mesh
    Body33: THREE.Mesh
    Body34: THREE.Mesh
    Body35: THREE.Mesh
    Body36: THREE.Mesh
    Body37: THREE.Mesh
    Body38: THREE.Mesh
    Body39: THREE.Mesh
    Body4: THREE.Mesh
    ['Body4_(1)']: THREE.Mesh
    Body40: THREE.Mesh
    Body41: THREE.Mesh
    Body42: THREE.Mesh
    Body43: THREE.Mesh
    Body5: THREE.Mesh
    Body6: THREE.Mesh
    Body7: THREE.Mesh
    Body8: THREE.Mesh
    ['Body8_(1)']: THREE.Mesh
    Body9: THREE.Mesh
    ['Body9_(1)']: THREE.Mesh
  }
  materials: {
    ['ABS (White)']: THREE.MeshStandardMaterial
    ['Steel - Satin']: THREE.MeshStandardMaterial
    ['3d texture rossa (2) (1)']: THREE.MeshStandardMaterial
  }
  animations: any// GLTFAction[]
}

const Model = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF('/models/tascabile/tascabile_v1.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <group position={[0, 54.06, -55.759]} rotation={[-1.617, 0, 0]}>
          <mesh geometry={nodes.Body1001.geometry} material={materials['Steel - Satin']} scale={10} />
        </group>
        <mesh geometry={nodes['Body1_(1)'].geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body1002.geometry} material={materials['ABS (White)']} scale={10} />
        <mesh geometry={nodes.Body10.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes['Body10_(1)'].geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body11.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes['Body11_(1)'].geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body12.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body13.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body14.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body15.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body16.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body17.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body18.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body19.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes['Body2_(1)'].geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body20.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body21.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body22.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body23.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body24.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body25.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body26.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body27.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body28.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body29.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body3.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body30.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body31.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body32.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body33.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body34.geometry} material={materials['3d texture rossa (2) (1)']} scale={10} />
        <mesh geometry={nodes.Body35.geometry} material={materials['3d texture rossa (2) (1)']} scale={10} />
        <mesh geometry={nodes.Body36.geometry} material={materials['3d texture rossa (2) (1)']} scale={10} />
        <mesh geometry={nodes.Body37.geometry} material={materials['3d texture rossa (2) (1)']} scale={10} />
        <mesh geometry={nodes.Body38.geometry} material={materials['3d texture rossa (2) (1)']} scale={10} />
        <mesh geometry={nodes.Body39.geometry} material={materials['3d texture rossa (2) (1)']} scale={10} />
        <mesh geometry={nodes.Body4.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes['Body4_(1)'].geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body40.geometry} material={materials['3d texture rossa (2) (1)']} scale={10} />
        <mesh geometry={nodes.Body41.geometry} material={materials['3d texture rossa (2) (1)']} scale={10} />
        <mesh geometry={nodes.Body42.geometry} material={materials['3d texture rossa (2) (1)']} scale={10} />
        <mesh geometry={nodes.Body43.geometry} material={materials['3d texture rossa (2) (1)']} scale={10} />
        <mesh geometry={nodes.Body5.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body6.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body7.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body8.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes['Body8_(1)'].geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body9.geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes['Body9_(1)'].geometry} material={materials['Steel - Satin']} scale={10} />
        <mesh geometry={nodes.Body1.geometry} material={materials['ABS (White)']} scale={10} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/tascabile/tascabile_v1.glb')

export default Model