/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\static\models\tascabile\tascabile_v3.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Body1: THREE.Mesh
    ['Body1_(1)']: THREE.Mesh
    ['Body1_(2)']: THREE.Mesh
    ['Body1_(3)']: THREE.Mesh
    Body10: THREE.Mesh
    Body11: THREE.Mesh
    ['Body11_(1)']: THREE.Mesh
    Body12: THREE.Mesh
    Body13: THREE.Mesh
    Body14: THREE.Mesh
    Body15: THREE.Mesh
    Body16001: THREE.Mesh
    Body16001_1: THREE.Mesh
    Body2: THREE.Mesh
    Body3: THREE.Mesh
    Body4: THREE.Mesh
    ['Body4_(1)']: THREE.Mesh
    Body5: THREE.Mesh
    Body6: THREE.Mesh
    Body7: THREE.Mesh
    Body8: THREE.Mesh
    ['Body8_(1)']: THREE.Mesh
    Body9: THREE.Mesh
    ['Body9_(1)']: THREE.Mesh
  }
  materials: {
    ['ABS (White).003']: THREE.MeshStandardMaterial
    ['Steel - Satin.002']: THREE.MeshStandardMaterial
    ['ABS (White).004']: THREE.MeshStandardMaterial
    ['3d texture rossa (2) (1).002']: THREE.MeshStandardMaterial
    ['3d txture celeste']: THREE.MeshStandardMaterial
  }
  animations: any // GLTFAction[]
}

const Model = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF('/models/tascabile/tascabile_v3.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
        <mesh geometry={nodes.Body1.geometry} material={materials['ABS (White).003']} scale={10} />
        <mesh geometry={nodes['Body1_(1)'].geometry} material={materials['ABS (White).003']} scale={10} />
        <mesh geometry={nodes['Body1_(2)'].geometry} material={materials['Steel - Satin.002']} scale={10} />
        <mesh geometry={nodes['Body1_(3)'].geometry} material={materials['ABS (White).004']} scale={10} />
        <mesh geometry={nodes.Body10.geometry} material={materials['Steel - Satin.002']} scale={10} />
        <mesh geometry={nodes.Body11.geometry} material={materials['Steel - Satin.002']} scale={10} />
        <mesh geometry={nodes['Body11_(1)'].geometry} material={materials['ABS (White).004']} scale={10} />
        <mesh geometry={nodes.Body12.geometry} material={materials['ABS (White).004']} scale={10} />
        <mesh geometry={nodes.Body13.geometry} material={materials['3d texture rossa (2) (1).002']} scale={10} />
        <mesh geometry={nodes.Body14.geometry} material={materials['ABS (White).004']} scale={10} />
        <mesh geometry={nodes.Body15.geometry} material={materials['ABS (White).004']} scale={10} />
        <group scale={10}>
          <mesh geometry={nodes.Body16001.geometry} material={materials['ABS (White).004']} />
          <mesh geometry={nodes.Body16001_1.geometry} material={materials['3d txture celeste']} />
        </group>
        <mesh geometry={nodes.Body2.geometry} material={materials['ABS (White).004']} scale={10} />
        <mesh geometry={nodes.Body3.geometry} material={materials['ABS (White).004']} scale={10} />
        <mesh geometry={nodes.Body4.geometry} material={materials['ABS (White).004']} scale={10} />
        <mesh geometry={nodes['Body4_(1)'].geometry} material={materials['Steel - Satin.002']} scale={10} />
        <mesh geometry={nodes.Body5.geometry} material={materials['ABS (White).004']} scale={10} />
        <mesh geometry={nodes.Body6.geometry} material={materials['ABS (White).004']} scale={10} />
        <mesh geometry={nodes.Body7.geometry} material={materials['ABS (White).004']} scale={10} />
        <mesh geometry={nodes.Body8.geometry} material={materials['Steel - Satin.002']} scale={10} />
        <mesh geometry={nodes['Body8_(1)'].geometry} material={materials['ABS (White).004']} scale={10} />
        <mesh geometry={nodes.Body9.geometry} material={materials['Steel - Satin.002']} scale={10} />
        <mesh geometry={nodes['Body9_(1)'].geometry} material={materials['ABS (White).004']} scale={10} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/tascabile/tascabile_v3.glb')

export default Model
