/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/a6/general.glb --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    sb2xsingola: THREE.Mesh
    sb1xdoppia: THREE.Mesh
    ['binder_per_a5,a6']: THREE.Mesh
    laccio: THREE.Mesh
    sidebar_a6: THREE.Mesh
    sidebarx2_a6: THREE.Mesh
    parte_sotto_a6: THREE.Mesh
    prova_2_cover_1_a6_v7_1: THREE.Mesh
    prova_2_cover_1_a6_v7_2: THREE.Mesh
    prova_2_cover_1_a6_v7_3: THREE.Mesh
    prova_2_cover_1_a6_v7_4: THREE.Mesh
    prova_2_cover_1_a6_v7_5: THREE.Mesh
    laccio001: THREE.Mesh
    laccio002: THREE.Mesh
    laccio003: THREE.Mesh
    laccio004: THREE.Mesh
    laccio005: THREE.Mesh
  }
  materials: {
    ['ABS_(bianco)']: THREE.MeshStandardMaterial
    ['ABS_(bianco).001']: THREE.MeshStandardMaterial
    ['ABS_(bianco).002']: THREE.MeshStandardMaterial
    ['ABS_(bianco).003']: THREE.MeshStandardMaterial
    ['ABS_(bianco).004']: THREE.MeshStandardMaterial
    ['ABS_(bianco).005']: THREE.MeshStandardMaterial
    ['ABS_(bianco).006']: THREE.MeshStandardMaterial
    ['ABS_(White)_(1)']: THREE.MeshStandardMaterial
    ['ABS_(bianco).007']: THREE.MeshStandardMaterial
    ['ABS_(bianco)_1']: THREE.MeshStandardMaterial
    ['3d_texture_rossa_(1)']: THREE.MeshStandardMaterial
    ['ABS_(bianco)_2']: THREE.MeshStandardMaterial
    ['ABS_(bianco).008']: THREE.MeshStandardMaterial
    ['ABS_(bianco).009']: THREE.MeshStandardMaterial
    ['ABS_(bianco).010']: THREE.MeshStandardMaterial
    ['ABS_(bianco).011']: THREE.MeshStandardMaterial
    ['ABS_(bianco).012']: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationAction[]
}

const Model = (props: JSX.IntrinsicElements['group']) => {
  const { nodes, materials } = useGLTF('/models/a6/general.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.sb2xsingola.geometry} material={materials['ABS_(bianco)']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.sb1xdoppia.geometry} material={materials['ABS_(bianco).001']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes['binder_per_a5,a6'].geometry} material={materials['ABS_(bianco).002']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.laccio.geometry} material={materials['ABS_(bianco).003']} position={[0.039, 0.038, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.sidebar_a6.geometry} material={materials['ABS_(bianco).004']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.sidebarx2_a6.geometry} material={materials['ABS_(bianco).005']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.parte_sotto_a6.geometry} material={materials['ABS_(bianco).006']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.prova_2_cover_1_a6_v7_1.geometry} material={materials['ABS_(White)_(1)']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.prova_2_cover_1_a6_v7_2.geometry} material={materials['ABS_(bianco).007']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.prova_2_cover_1_a6_v7_3.geometry} material={materials['ABS_(bianco)_1']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.prova_2_cover_1_a6_v7_4.geometry} material={materials['3d_texture_rossa_(1)']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.prova_2_cover_1_a6_v7_5.geometry} material={materials['ABS_(bianco)_2']} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.laccio001.geometry} material={materials['ABS_(bianco).008']} position={[0.039, 0.038, -0.563]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.laccio002.geometry} material={materials['ABS_(bianco).009']} position={[0.077, 0, -1.147]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.laccio003.geometry} material={materials['ABS_(bianco).010']} position={[0.077, 0.053, -0.491]} rotation={[-1.575, 0, 0]} />
      <mesh geometry={nodes.laccio004.geometry} material={materials['ABS_(bianco).011']} position={[0.039, 0.013, -1.075]} rotation={[-1.575, 0, 0]} />
      <mesh geometry={nodes.laccio005.geometry} material={materials['ABS_(bianco).012']} position={[0.039, 0.01, -1.638]} rotation={[-1.575, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/a6/general.glb')

export default Model